version: '3.9'
services:
  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Port=5432;Database=rideOutDB;User Id=kb;Password=Babyboy1228!
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kb
      POSTGRES_PASSWORD: Babyboy1228!
      POSTGRES_DB: rideOutDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ../Client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  postgres_data:
